// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { Application } from "@hotwired/stimulus"
import HelloController from "./hello_controller"
import Autocomplete from "stimulus-autocomplete"
import CounterController from "./counter_controller"
import OnboardingController from "./onboarding_controller"

export const application = Application.start()
application.register("hello", HelloController)
application.register("autocomplete", Autocomplete)
application.register("counter", CounterController)
application.register("onboarding", OnboardingController)

