services:
  - type: web
    name: myapp
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: myapp-db
          property: connectionString

databases:
  - name: myapp-db
    plan: free